apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: enterprise-logs-role
rules:
##
## Rules for grafana.com/v1alpha1, Kind: Grafana
##
- apiGroups:
  - grafana.com
  resources:
  - grafanas
  - grafanas/status
  - grafanas/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "persistentvolumeclaims"
  - "secrets"
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "statefulsets"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- apiGroups:
  - security.openshift.io
  resourceNames:
  - hostmount-anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
